PruebaBertoni/PruebaBertoni/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PruebaBertoni.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PruebaBertoni/PruebaBertoni/Controllers/OperacionesController.cs
using Dominio.Core.Entities;
using Dominio.Core.MainModule;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace PruebaBertoni.Controllers
{
    public class OperacionesController : Controller
    {
        AlbumManager albumManager = new AlbumManager();
        FotoManager fotoManager = new FotoManager();
        ComentariosManager comentariosManager = new ComentariosManager();
       
        public async Task<ActionResult> Album() {

            var list = await albumManager.listAlbum();

            return View(list);


        }

        public async Task<ActionResult> Fotos(int id_album)
        {

            var list = await fotoManager.listFoto(id_album);

            return View(list);


        }

        public async Task<ActionResult> Comentarios(int id_foto)
        {

            var list = await comentariosManager.listComentarios(id_foto);

            return Json(list, JsonRequestBehavior.AllowGet);


        }

    }
}

PruebaBertoni/PruebaBertoni/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PruebaBertoni/PruebaBertoni/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PruebaBertoni/PruebaBertoni/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PruebaBertoni/PruebaBertoni/Views/Operaciones/Album.cshtml
@model IEnumerable<Dominio.Core.Entities.Album>

@{
    ViewBag.Title = "Album";
}

<h2>Album</h2>

<form method="post" action="@Url.Action("Fotos", "Operaciones")">

    <div class="form-group">
        <select class="form-control" name="id_album">

            @foreach (var item in Model)
            {
                <option value="@item.id">@item.title</option>

            }

        </select>
    </div>
    <button class="btn btn-primary" type="submit">Vizualizar Album</button>

</form>

PruebaBertoni/PruebaBertoni/Views/Operaciones/Fotos.cshtml
@model IEnumerable<Dominio.Core.Entities.Foto>

@{
    ViewBag.Title = "Fotos";
}

<h2>Fotos</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.albumId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.albumId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.thumbnailUrl)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.albumId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.title)
    </td>
    <td class="ocultar" hidden>
        @item.url />
    </td>
    <td>
        <img src="@item.thumbnailUrl" />
    </td>

    <td>
        <button id="idComentarios" type="button" class="btn btn-primary">Ver Comentarios</button>

    </td>
</tr>
    }

</table>

<br />



<table id="tabla" class="table table-responsive table-bordered">
    <tr class="cabecera">
    
    </tr>

    <tr>

        <td>Id</td>
        <td>Nombre</td>
        <td>Email</td>
        <td>Comentario</td>

    </tr>
   


 

</table>

PruebaBertoni/PruebaBertoni/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        $(document).on("click", "#idComentarios", function () {
            var id_foto = $(this).parents("tr").find("td")[1].innerHTML;
            alert(id_foto);
            
            var url = $(this).parents("tr").find("td.ocultar").html();
         

         
                $.ajax({
                    url: "/Operaciones/Comentarios",
                    contentType: "application/json; charset=utf-8",

                    type: "GET",
                    data: {id_foto:id_foto},
                    dataType: "json",
                    success: function (respuesta) {
                        $("#tabla").find(".seccioncabecera").remove();
                        $("#tabla .cuerpo").remove();
                       
                        $("#tabla").find(".cabecera").append("  <td class='seccioncabecera' colspan='4'><center> <img src=" + url +"/></center></td>")
                        $.each(respuesta, function (index, elemento) {
                          
                            $("#tabla").append("<tbody class='cuerpo'><tr class='seccioncomentarios'><td>" + elemento.id + "</td><td>" + elemento.name + "</td><td>" + elemento.email + "</td><td>" + elemento.body + "</td></tr> </tbody>"
                              
                              
                            );
                        });
                    },
                    error: function () {
                        alert(id_foto);
                    }
             
        })

        })

    </script>
</body>
</html>